from odoo.tests import HttpCase


class TestPhantomTour(HttpCase):

    def _test_phantom_tour(self, start_url, tour_name, **kw):
        """ Wrapper to run web tours
        """
        tour_service = "odoo.__DEBUG__.services['web_tour.tour']"
        js_run_tour = tour_service + ".run('%s')"
        js_tours_tour = tour_service + ".tours.%s.ready"
        self.browser_js(
            url_path=start_url,
            code=js_run_tour % tour_name,
            ready=js_tours_tour % tour_name,
            **kw)

    def _test_phantom_tour_requests(self, start_url, tour_name, **kw):
        """ Same as _test_phantom_tour but returns list of requests
            generated by tour
        """
        requests_before = self.env['request.request'].search([])
        self._test_phantom_tour(start_url, tour_name, **kw)
        requests_new = self.env['request.request'].search(
            [('id', 'not in', requests_before.ids)])
        return requests_new
